<!-- QUE AL PULSAR EL BOTON DE VER DATOS SE ABRA UNA VENTANA EMERGENTE, 
 ES DECIR, COMO UNA ALERTA, PARA VER LOS DATOS, Y QUE ESTEN LOS BOTONES 
 DE CERRAR VENTANA, EDITAR DATOS Y DARSE DE BAJA (QUE LA ACCION SE PUEDA 
 HACER DESDE VARIOS SITIOS EN LUGAR DE SOLO EL SIDEBAR) -->